"use client";

import { Check, KeyRound } from "lucide-react";
import { DEFAULT_ROLE_PERMISSIONS, LEGACY_ROLE_NAMES, PERMISSION_CATEGORIES, PERMISSION_LABELS, type Permission } from "@/shared/types/types";
import { useLanguage } from "@/shared/hooks/LanguageContext";

export default function AdminPermissionsPage() {
  const { language } = useLanguage();
  const roles = Object.keys(DEFAULT_ROLE_PERMISSIONS).filter((role) => !LEGACY_ROLE_NAMES.includes(role as typeof LEGACY_ROLE_NAMES[number]));
  return <div className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 sm:p-6"><div className="mx-auto max-w-[1200px]"><div className="flex gap-4 rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300"><KeyRound className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">{language === "km" ? "សិទ្ធិដែលបានអនុវត្ត" : "Enforced access"}</p><h1 className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{language === "km" ? "ការអនុញ្ញាត" : "Permissions"}</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{language === "km" ? "តារាងនេះបង្ហាញសិទ្ធិពិតប្រាកដដែលកម្មវិធីកំពុងអនុវត្ត" : "This matrix shows the real permissions currently enforced by the application."}</p></div></div><div className="mt-5 space-y-5">{Object.entries(PERMISSION_CATEGORIES).map(([category, permissions]) => <section key={category} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="border-b border-slate-200 bg-slate-50 px-5 py-4 font-bold text-slate-900 dark:border-slate-800 dark:bg-slate-950 dark:text-white">{category}</h2><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-100 text-slate-500 dark:border-slate-800 dark:text-slate-400"><tr><th className="px-5 py-3 font-semibold">Permission</th>{roles.map((role) => <th key={role} className="px-5 py-3 text-center font-semibold">{role}</th>)}</tr></thead><tbody>{(permissions as readonly Permission[]).map((permission) => <tr key={permission} className="border-b border-slate-100 last:border-b-0 dark:border-slate-800"><td className="px-5 py-3 font-medium text-slate-800 dark:text-slate-200">{PERMISSION_LABELS[permission]}</td>{roles.map((role) => <td key={role} className="px-5 py-3 text-center">{DEFAULT_ROLE_PERMISSIONS[role]?.includes(permission) ? <Check className="mx-auto h-4 w-4 text-emerald-600 dark:text-emerald-300" aria-label="Allowed" /> : <span className="text-slate-300 dark:text-slate-700">—</span>}</td>)}</tr>)}</tbody></table></div></section>)}</div></div></div>;
}
